# Generated by Django 3.2.9 on 2021-12-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('richmenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='richmenu',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
