# Generated by Django 3.2.9 on 2021-12-05 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('starttime', models.DateTimeField(blank=True, null=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('hours', models.IntegerField(blank=True, null=True)),
                ('user_order_ls', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'badminton"."appointment',
            },
        ),
        migrations.CreateModel(
            name='HourDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_cnt', models.IntegerField(blank=True, null=True)),
                ('people_cnt', models.IntegerField(blank=True, null=True)),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment')),
            ],
            options={
                'db_table': 'badminton"."hour_detail',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank=True, null=True)),
                ('hour_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.hourdetail')),
            ],
            options={
                'db_table': 'badminton"."invitation',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.TextField(blank=True, null=True)),
                ('role', models.TextField(blank=True, null=True)),
                ('line_uid', models.TextField()),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('hourdetails', models.ManyToManyField(through='appointments.Invitation', to='appointments.HourDetail')),
            ],
            options={
                'db_table': 'badminton"."user',
            },
        ),
        migrations.AddField(
            model_name='invitation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.user'),
        ),
    ]
