# Generated by Django 3.2.9 on 2021-12-05 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourdetail',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hour_details', to='appointments.appointment'),
        ),
    ]
