# Generated by Django 3.2.9 on 2021-12-05 20:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_alter_appointment_user_order_ls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='user_order_ls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
